version: '3' # vs mais atual

services: 
  serve: 
    build: serve
    container_name: ragnarok-app
    restart: always
    tty: true
    working_dir: /emulador
    # SEMPRE QUE REINICIAR O CONTAINER IRAR BUIDAR O EMULADOR
    # command:  bash -c "dos2unix -f entrypoint.sh && chmod a+x entrypoint.sh && ./entrypoint.sh"
    volumes:
      # LEMBRAR SUBISTITUIR O NOME <EMULADOR> PARA A PASTE DO SEU SERVER
      - ./serve/emulador:/emulador
    ports:
      - "5121:5121"
      - "6121:6121"
      - "6900:6900"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIRECT_STATUS=true
    networks:
      - ragnarok-app-network
    depends_on: 
      - db
      
  db:
    build: db
    container_name: ragnarok-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./db/dbdata:/var/lib/mysql
      - ./db/sql-files:/docker-entrypoint-initdb.d
      - ./db/log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=ragnarok
      - MYSQL_ROOT_PASSWORD=R00t+
      - MYSQL_USER=ragnarok
      - MYSQL_PASSWORD=ragnarok
    networks:
      - ragnarok-app-network
              
networks:
  ragnarok-app-network:
    driver: bridge
